name: platinumbetss
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  path_provider: ^1.1.0
  firebase_core: ^0.4.0+9
  http: ^0.12.2
  flutter_staggered_grid_view: ^0.3.0
  cloud_firestore: ^0.12.9
  carousel_pro: ^1.0.0
  transparent_image: ^1.0.0
  scoped_model: ^1.0.1
  firebase_auth: ^0.11.1+12
  url_launcher: ^5.1.1
  firebase_analytics: ^5.0.2
  expandable: ^4.1.4

dev_dependencies:

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/imagens/comemorar.jpg
    - assets/imagens/FundoLogin.jpg
    - assets/imagens/Gigachad.jpg
    - assets/imagens/Quadra.jpg
    - assets/imagens/DegradePerfil.png
    # NBA Logos
    - assets/imagens/times/nba/Atlanta-Hawks.png
    - assets/imagens/times/nba/Boston-Celtics.png
    - assets/imagens/times/nba/Brooklyn-Nets.png
    - assets/imagens/times/nba/Charlotte-Hornets.png
    - assets/imagens/times/nba/Chicago-Bulls.png
    - assets/imagens/times/nba/Cleveland-Cavaliers.png
    - assets/imagens/times/nba/Dallas-Mavericks.png
    - assets/imagens/times/nba/Denver-Nuggets.png
    - assets/imagens/times/nba/Detroit-Pistons.png
    - assets/imagens/times/nba/Golden-State-Warriors.png
    - assets/imagens/times/nba/Houston-Rockets.png
    - assets/imagens/times/nba/Indiana-Pacers.png
    - assets/imagens/times/nba/Los-Angeles-Clippers.png
    - assets/imagens/times/nba/Los-Angeles-Lakers.png
    - assets/imagens/times/nba/Memphis-Grizzlies.png
    - assets/imagens/times/nba/Miami-Heat.png
    - assets/imagens/times/nba/Milwaukee-Bucks.png
    - assets/imagens/times/nba/Minnesota-Timberwolves.png
    - assets/imagens/times/nba/New-Orleans-Pelicans.png
    - assets/imagens/times/nba/New-York-Knicks.png
    - assets/imagens/times/nba/Oklahoma-City-Thunder.png
    - assets/imagens/times/nba/Orlando-Magic.png
    - assets/imagens/times/nba/Philadelphia-76ers.png
    - assets/imagens/times/nba/Phoenix-Suns.png
    - assets/imagens/times/nba/Portland-Trail-Blazers.png
    - assets/imagens/times/nba/Sacramento-Kings.png
    - assets/imagens/times/nba/San-Antonio-Spurs.png
    - assets/imagens/times/nba/Toronto-Raptors.png
    - assets/imagens/times/nba/Utah-Jazz.png
    - assets/imagens/times/nba/Washington-Wizards.png
    - assets/imagens/times/brSerieA/Athletico-PR.png
    - assets/imagens/times/brSerieA/Atletico-GO.png
    - assets/imagens/times/brSerieA/Atletico-MG.png
    - assets/imagens/times/brSerieA/Bahia.png
    - assets/imagens/times/brSerieA/Botafogo.png
    - assets/imagens/times/brSerieA/Bragantino.png
    - assets/imagens/times/brSerieA/Ceara-SC.png
    - assets/imagens/times/brSerieA/Corinthians.png
    - assets/imagens/times/brSerieA/Coritiba.png
    - assets/imagens/times/brSerieA/Flamengo.png
    - assets/imagens/times/brSerieA/Fluminense.png
    - assets/imagens/times/brSerieA/Fortaleza.png
    - assets/imagens/times/brSerieA/Goias.png
    - assets/imagens/times/brSerieA/Gremio.png
    - assets/imagens/times/brSerieA/Internacional.png
    - assets/imagens/times/brSerieA/Palmeiras.png
    - assets/imagens/times/brSerieA/Santos.png
    - assets/imagens/times/brSerieA/Sao-Paulo.png
    - assets/imagens/times/brSerieA/Sport-Recife.png
    - assets/imagens/times/brSerieA/Vasco-da-Gama.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
